@startuml
title Sequence diagram for read

participant ReaderThread
participant Reader
participant RingBuffer

ReaderThread -> Reader : read()
activate Reader
Reader -> RingBuffer : oldestAvailableSeqUnsafe()
RingBuffer --> Reader : oldestAvailableSeq
Reader -> RingBuffer : writeSeqUnsafe()
RingBuffer --> Reader : writeSeq

alt [reader fell behind]
  Reader -> Reader : nextSeqToRead = oldestAvailableSeq
end

alt [no new item]
  Reader --> ReaderThread : Optional.empty()
else [item available]
  Reader -> RingBuffer : getAtSeqUnsafe(nextSeqToRead)
  RingBuffer --> Reader : item
  Reader -> Reader : nextSeqToRead++
  Reader --> ReaderThread : Optional.of(item)
end

deactivate Reader
@enduml
