@startuml
title Sequence diagram for write

participant WriterThread
participant Writer
participant RingBuffer

loop [until interrupted]
  WriterThread -> Writer : run()
  Writer -> RingBuffer : write(value)
  activate RingBuffer
  RingBuffer -> RingBuffer : data[writeIndex] = value\nwriteIndex = (writeIndex+1) % capacity\nwriteSeq++
  deactivate RingBuffer
end

@enduml
